Replace the old Github workflow with the new one

diff --git a/.github/workflows/manual-build-and-publish-image.yaml b/.github/workflows/manual-build-and-publish-image.yaml
--- a/.github/workflows/manual-build-and-publish-image.yaml
+++ b/.github/workflows/manual-build-and-publish-image.yaml
@@ -3,30 +3,62 @@ name: Manual build and publish a container image
 on:
   workflow_dispatch:
     inputs:
-      baseImageTag:
-        description: 'Base image tag'
+      baseImage:
+        description: "Base image"
         required: true
-        default: 2.2.0-gpu-jupyter
+        default: tensorflow/tensorflow:2.2.0-gpu-jupyter
         type: choice
         options:
-          - 2.2.0-gpu-jupyter
-          - 2.2.0-gpu
-          - 2.2.1-gpu-jupyter
-          - 2.2.1-gpu
-          - 2.2.3-gpu-jupyter
-          - 2.2.3-gpu
-          - 2.3.4-gpu-jupyter
-          - 2.3.4-gpu
-          - 2.4.3-gpu-jupyter
-          - 2.4.3-gpu
-
+          - tensorflow/tensorflow:2.2.0-gpu-jupyter
+          - tensorflow/tensorflow:2.2.0-gpu
+          - tensorflow/tensorflow:2.2.1-gpu-jupyter
+          - tensorflow/tensorflow:2.2.1-gpu
+          - tensorflow/tensorflow:2.2.3-gpu-jupyter
+          - tensorflow/tensorflow:2.2.3-gpu
+          - tensorflow/tensorflow:2.3.4-gpu-jupyter
+          - tensorflow/tensorflow:2.3.4-gpu
+          - tensorflow/tensorflow:2.4.3-gpu-jupyter
+          - tensorflow/tensorflow:2.4.3-gpu
+          - nvcr.io/nvidia/pytorch:21.12-py3
 env:
   REGISTRY: ghcr.io
-  IMAGE_NAME: ${{ github.repository }}
+  REPO_NAME: ${{ github.repository }}
+  BASE_IMAGE: ${{ inputs.baseImage }}
 
 jobs:
+  map_inputs:
+    runs-on: ubuntu-latest
+    outputs:
+      baseImageTag: "${{ steps.step1.outputs.BASE_IMAGE_TAG }}"
+      baseImageName: "${{ steps.step1.outputs.BASE_IMAGE_NAME }}"
+      imageName: "${{ steps.step1.outputs.IMAGE_NAME }}"
+      imageTag: "${{ steps.step1.outputs.IMAGE_TAG }}"
+    steps:
+      - id: step1
+        run: |
+          BASE_IMAGE_TAG=${BASE_IMAGE#*:};
+          BASE_IMAGE_NAME=${BASE_IMAGE%%:*};
+          case "$BASE_IMAGE_NAME" in
+            tensorflow/tensorflow) IMAGE_NAME=$GITHUB_REPOSITORY_OWNER/tensorflow-code-server;;
+            nvcr.io/nvidia/pytorch) IMAGE_NAME=$GITHUB_REPOSITORY_OWNER/pytorch-code-server;;
+            *) echo >&2 "Error: unknown base image: $BASE_IMAGE_NAME"; exit 1;;
+          esac;
+          IMAGE_TAG=$BASE_IMAGE_TAG;
+          printf "BASE_IMAGE_TAG=%q\n" "$BASE_IMAGE_TAG"   >> $GITHUB_OUTPUT;
+          printf "BASE_IMAGE_NAME=%q\n" "$BASE_IMAGE_NAME" >> $GITHUB_OUTPUT;
+          printf "IMAGE_NAME=%q\n" "$IMAGE_NAME"           >> $GITHUB_OUTPUT;
+          printf "IMAGE_TAG=%q\n" "$IMAGE_TAG"             >> $GITHUB_OUTPUT;
+          echo "### \`map_inputs\`"               >> $GITHUB_STEP_SUMMARY;
+          echo "BASE_IMAGE=$BASE_IMAGE"           >> $GITHUB_STEP_SUMMARY;
+          echo "BASE_IMAGE_TAG=$BASE_IMAGE_TAG"   >> $GITHUB_STEP_SUMMARY;
+          echo "BASE_IMAGE_NAME=$BASE_IMAGE_NAME" >> $GITHUB_STEP_SUMMARY;
+          echo "IMAGE_NAME=$IMAGE_NAME"           >> $GITHUB_STEP_SUMMARY;
+          echo "IMAGE_TAG=$IMAGE_TAG"             >> $GITHUB_STEP_SUMMARY;
+          echo ""                                 >> $GITHUB_STEP_SUMMARY;
+
   build-and-push-image:
     runs-on: ubuntu-latest
+    needs: map_inputs
     permissions:
       contents: read
       packages: write
@@ -46,14 +78,14 @@ jobs:
         id: meta
         uses: docker/metadata-action@v4
         with:
-          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
+          images: ${{ env.REGISTRY }}/${{ needs.map_inputs.outputs.imageName }}
 
       - name: Build and push Docker image
         uses: docker/build-push-action@v3
         with:
           context: .
           push: true
-          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.baseImageTag }}
+          tags: ${{ env.REGISTRY }}/${{ needs.map_inputs.outputs.imageName }}:${{ needs.map_inputs.outputs.imageTag }}
           labels: ${{ steps.meta.outputs.labels }}
           build-args: |
-            BASE_IMAGE=tensorflow/tensorflow:${{ inputs.baseImageTag }}
+            BASE_IMAGE=${{ env.BASE_IMAGE }}
